### ISSUE TITLE
kmrについての質問です

### ISSUE THREAD

**Issue by bocchan** [bocchan/kmr#1]
import numpy as np

def kmr_markov_matrix(p=1/3, N=4, epsilon=0.01):
    P = np.empty((N+1, N+1))
    P[0,0] = 1 - epsilon
    P[0,1] = epsilon
    for n in range(1, N):
        if (n-1)/(N-1) < p:
            a1_ratio = (n-1)/(N-1)
        elif (n-1)/(N-1) == p:
            a1_ratio = (n-1)/(N-1)/2
        P[n, n-1] = (n/N) \* ((epsilon/2) + (1-epsilon)*(a1_ratio))
        if (n / (N-1)) > p:
            a2_ratio = n / (N-1)
        elif n / (N-1) == p:
            a2_ratio = n / (N-1) / 2
        P[n, n+1] = ((N-n)/N) \* ((epsilon/2) + ((1-epsilon) \* a2_ratio)
        P[n, n] = 1 - P[n, n-1] - P[n, n+1]
（ipython上ではインデントしてます）
このようなコードを書いてやってみましたが、
P[ ]を用いている部分でなぜか出てくる、syntax errorが直りません。

p=1/3
N=4 
epsilon=0.01
P = np.empty((N+1, N+1))
for n in range(0, N):
    P[n, n+1] = 1
print P
このようにするとちゃんとマトリックスが表示されます。上の例はどこが問題なのでしょうか。

**Comment by oyamad** [comment]
読めないので，下のように ```python と ``` とでコードブロックを囲ってください (インデントもふつうに4つずつスペースを入れる)．

```python
import numpy as np

def kmr_markov_matrix(p=1/3, N=4, epsilon=0.01):
&nbsp;&nbsp;&nbsp;&nbsp;P = np.empty((N+1, N+1))
```

表示され方

``` python
import numpy as np

def kmr_markov_matrix(p=1/3, N=4, epsilon=0.01):
    P = np.empty((N+1, N+1))
```

あと syntax error の全文も載せてください．

**Comment by bocchan** [comment]
ありがとうございます、以下の通りです。

``` python
import numpy as np

def kmr_markov_matrix(p=1/3, N=4, epsilon=0.01):
    P = np.empty((N+1, N+1))
    P[0,0] = 1 - epsilon
    P[0,1] = epsilon
    for n in range(1, N):
        if (n-1)/(N-1) < p:
            a1_ratio = (n-1)/(N-1)
        elif (n-1)/(N-1) == p:
            a1_ratio = (n-1)/(N-1)/2
        P[n, n-1] = (n/N) * ((epsilon/2) + (1-epsilon)*(a1_ratio))
        if (n / (N-1)) > p:
            a2_ratio = n / (N-1)
        elif n / (N-1) == p:
            a2_ratio = n / (N-1) / 2
        P[n, n+1] = ((N-n)/N) * ((epsilon/2) + ((1-epsilon) * a2_ratio)
        P[n, n] = 1 - P[n, n-1] - P[n, n+1]
  File "<ipython-input-2-ed89019828a4>", line 18
    P[n, n] = 1 - P[n, n-1] - P[n, n+1]
    ^
SyntaxError: invalid syntax
```

``` python
p=1/3
N=4 
epsilon=0.01
P = np.empty((N+1, N+1))
for n in range(0, N):
    P[n, n+1] = 1
print P
```

**Comment by oyamad** [comment]
`SyntaxError` の1行前で左右のカッコの数が合っていません．

**Comment by bocchan** [comment]
通りました、ありがとうございます！
初歩的な間違いをお聞きしてすみませんでした。
