### ISSUE TITLE
質問２です

### ISSUE THREAD

**Issue by bocchan** [bocchan/kmr#2]
![image](https://cloud.githubusercontent.com/assets/12110362/8690108/0a1b313e-2aeb-11e5-94c0-78a31cce1c38.png)
自分では、(N+1)×(N+1)の行列を用意しているつもりなのですが、out of boundsと言われてしまいます。kmrクラスの中身はほぼ先ほどのコードのままです。よろしくお願いします。

**Comment by oyamad** [comment]
`KMR` インスタンスを作るときに `KMR(N, p, epsilon)` になってます． `KMR(p, N, epsilon)` というデザインなのではないですか．

あと，冒頭で

``` python
from __future__ import division
```

と宣言しないと，`1/3` は切り捨てられて `0`  になります．

**Comment by bocchan** [comment]
ありがとうございます！
引数は変数名ではなくて、順番で決まっているのですね。
Pを作るところまでは通りました。
