### ISSUE TITLE
質問３です。

### ISSUE THREAD

**Issue by bocchan** [bocchan/kmr#3]
たびたびすみません、
![image](https://cloud.githubusercontent.com/assets/12110362/8690981/2418cf4a-2af7-11e5-8471-484baba9c3ea.png)
以下のようなエラーが返ってきます。
printしたＰは7×7になっているようなので、self.P.shapeをしたときに何か不都合があるのかと思い、https://github.com/QuantEcon/QuantEcon.py/blob/master/quantecon/mc_tools.py
を参照してみましたが、P.shapeが何をしているのかわかりませんでした。
よろしくお願いします。

**Comment by oyamad** [comment]
`P` が2次元配列になっていないか，2次元配列になっていても n x n になっていない，というエラーです．

`kmr.py` の中身を見ないとわからないので，プッシュして．
(`kmr_markov_matrix` の中で最後に `return P` してる？)

**Comment by bocchan** [comment]
ありがとうございます！
return P
をしていないだけでした...
すみませんでした。
